### ISSUE TITLE
Plotting the spectrum in stft model does not work. (with fix)

### ISSUE THREAD

**Issue by matz78** [MTG/sms-tools#52] opened 2017-04-15 18:59 UTC
When I try to plot the result of stft, the spectrum is missing, and in
software/models_interface/stft_function.py
in lines 59 and 70 I got the error 'TypeError: slice indices must be integers or None or have an __index__ method'
I could fix it by casting the index to int, and now the plot works again
l. 59 plt.pcolormesh(frmTime, binFreq, np.transpose(mX[:,:int(N*maxplotfreq/fs+1)]))
l. 70 plt.pcolormesh(frmTime, binFreq, np.transpose(np.diff(pX[:,:int(N*maxplotfreq/fs+1)],axis=1)))

**Comment by DavidAntliff** [comment] 2017-04-23 22:18
This is a duplicate of #49

**Comment by xserra** [comment] 2017-08-14 11:36
fixed

**Closed by xserra** 2017-08-14 11:36 UTC
