### ISSUE TITLE
Transformations_GUI issues on Python 3.11.1 (and 3.9.6)

### ISSUE THREAD

**Issue by leximAI** [MTG/sms-tools#140] opened 2023-01-25 05:25 UTC
Clicking on Analysis results in the following error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "sms-tools\software\transformations_interface\sineTransformations_GUI_frame.py", line 180, in analysis
    self.inputFile, self.fs, self.tfreq, self.tmag = sT.analysis(inputFile, window, M, N, t, minSineDur, maxnSines, freqDevOffset, freqDevSlope)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\sms-tools\software\transformations_interface\sineTransformations_function.py", line 41, in analysis
    tfreq, tmag, tphase = SM.sineModelAnal(x, fs, w, N, H, t, maxnSines, minSineDur, freqDevOffset, freqDevSlope)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sms-tools\software\transformations_interface\../models\sineModel.py", line 166, in sineModelAnal
    tfreq, tmag, tphase = sineTracking(ipfreq, ipmag, ipphase, tfreq, freqDevOffset, freqDevSlope)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sms-tools\software\transformations_interface\../models\sineModel.py", line 25, in sineTracking
    pindexes = np.array(np.nonzero(pfreq), dtype=np.int)[0]  # indexes of current peaks
                                                 ^^^^^^
  File "AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'

**Comment by marcoslhc** [comment] 2023-01-27 04:24
This happens because numpy removed support for `np.float` in version 1.24.
this PR is a workaround: https://github.com/MTG/sms-tools/pull/141

**Comment by alastair** [comment] 2024-09-17 10:58
Duplicate of #139

**Closed by alastair** 2024-09-17 10:58 UTC
